In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plb

This is a dataset where, the high energy gamma particles are registered.

In [3]:
pd.read_csv("E:\magic_gamma_telescope\magic04.data")

,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.011,-8.2027,40.092,81.8828,g
0,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
1,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
2,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
3,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
4,51.6240,21.1502,2.9085,0.2420,0.1340,50.8761,43.1887,9.8145,3.6130,238.0980,g
...,...,...,...,...,...,...,...,...,...,...,...
19014,21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
19015,28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
19016,75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
19017,120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
19018,187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

In [ ]:
cols = ["fLength", "fWidth", "fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"] #These are the columns provided already by the dataset provider
df = pd.read_csv("E:\magic_gamma_telescope\magic04.data", names = cols) # Here, names is the attribute where, we can provide the column name
df

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist
28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
...,...,...,...,...,...,...,...,...,...,...
21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

In [ ]:
df.head() # We'll get first five elements generally.

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist
28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g

In [9]:
df['fLength']

28.7967      16.0021
31.6036      11.7235
162.0520    136.0310
23.8172       9.5728
75.1362      30.9205
              ...
21.3846      10.9170
28.9452       6.7020
75.4455      47.5305
120.5135     76.9018
187.1814     53.0014
Name: fLength, Length: 19020, dtype: float64

In [10]:
# Here, one mistake what I have done is, I have provided only 10 columns, but, 11 columns are there. So, Pandas automatically takes the first some values which does not column name.
# So, here, the first value became the dataframe index. 
# Now, I have a doubt that, what if, two columns are less?
# I'm going to check that.. 

cols = ["fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist"] # Here, I have provided only seven columns, but 11 are present.
df1 = pd.read_csv("E:\magic_gamma_telescope\magic04.data", names = cols) 
df1

,,,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist
28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
...,...,...,...,...,...,...,...,...,...,...
21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

In [ ]:
# So, here, the first set of columns where the column name can't be matched is left. Here also, the first column is becoming the dataframe index. 
# Lets check that also.. 

df['fSize'][28.7967]

# Yeah, the first column is acting as dataframe index...

np.float64(0.3918)

In [12]:
cols = ["fLength", "fWidth", "fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"] #These are the columns provided already by the dataset provider
df = pd.read_csv("E:\magic_gamma_telescope\magic04.data", names = cols) # Here, names is the attribute where, we can provide the column name
df

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.0110,-8.2027,40.0920,81.8828,g
1,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
2,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
3,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
4,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
...,...,...,...,...,...,...,...,...,...,...,...
19015,21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
19016,28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
19017,75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
19018,120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
19019,187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

In [13]:
df['class'].unique()

#This unique function helps to get the unique values in the column...

array(['g', 'h'], dtype=object)

Here, we are planning to use astype() function. This function is helpful in converting the dataframe from one datatype to another datatype. 
The syntax is 
dataframe.astype(dtype, copy=True | False, errors='raise' | 'ignore')

In [14]:
df['class'] = (df['class'] == 'g').astype('int')

In [24]:
df['class'].unique()  # This returns an numpy array of unique values in the table.

array([1, 0])

Features are columns in the dataset that help the model to understand the pattern to predict the label.

Here, as the class is known, this learning is called Supervised learning..
In Unsupervised learning, there won't be any classes. The model's main part is grouping or clustering.
In Reinforcement learning, there is an agent (Not an agent in current Generative AI sense) which learns in interactive environment based on rewards and penalties.

Qualitative features describe a non numerical characteristic, category or label. They can't be measured with numbers but instead, a quality or category such as an item's color, etc. 

There are two types:
1. Nominal features - Categories with no logical order or hierarchy.
2. Ordinal features - Categories that have a meaningful order or ranking.

For non ordinal features, one hot encoding is a best choice. For eg, if there are three colours, say Red, Green and Blue, one hot encoding creates three extra columns such as is_red, is_green and is_blue. If the colour is red, the is_red column will become 1, and so on. Without this, if we encode Red as 1, Blue as 2 and Green as 3, then, ML models may create an unwanted linear hierarchical relationship between the columns, with which, the prediction might go wrong.

This may affect at the places where, the Linear models, Distance based models or Gradient based optimization might be used as, there is a possibility for those models to learn a different, unwanted, wrong relationship between the color encoding and the other features.

For ordinal categories such as bad, satisfactory, neutral, good and great, the encoding can be given as 1, 2, 3, 4 and 5. The Distance based models can analyse and understand how related Good and Bad are, etc.

Quantitative features describe a numeric characteristic, category or label. They represent numeric quantities. There are two types in that.

1. Discrete Quantitative Features - Countable quantities, Values are usually integers because you count individual items. Eg: Number of users, Number of packets transmitted.
2. Continuous Quantitative Features - Measurable quantities, Can take any value within a range, including decimals. Eg: Height, Weight, Temperature etc.

No encoding is needed here, as they are already Math.

In supervised learning, the Model can predict discrete classes. (Multiclass Classification, Binary classification)

For Binary Classification, Eg: Positive / negative, Cat / dog, Spam / not spam

For Multiclass Classification, Eg: Cat/dog/lizard/dolphin, Orange/apple/pear, Plant species

The Model can also predict Continuous values - Regression
Eg: Price of the house, Price of the asset, etc.

Feature vector - Features in one sample
Feature matrix - Features of all the samples

The whole dataset is split into Training dataset, Validation dataset and testing dataset (60%, 20%, 20% respectively or 80%, 10%, 10% anything)...

While using Training dataset, we'll make the model predict the output and check how close the prediction is aligned with the output. The difference between the prediction and the actual value is called Loss.
With the Loss, we'll make adjustments. So, in training, the feedback loop happens.

Then, we'll check whether the model can handle unseen data using the validation set. 

With the validation set, we'll evaluate which model is good on the comparison, with which, at the end, the model is tested with the Test set, where, the performance is analysed.

Loss - Difference between the Prediction and the actual label.

Some Loss functions:
1. L1 Loss = sum(|y_real - y_predicted|)
Here, sum is done to add the Loss values of each and every entry of the dataset and with that, the overall Loss is found.
2. L2 loss = sum((y_real - y_predicted) ^ 2)
3. Binary Cross Entropy Loss (A big formula)
- Here, when the performance increases, the loss decreases and vice versa.