This is the notebook where, I'm practicing the basics of pandas.

In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

df.head() provides the first five rows of the dataframe, similarly, df.tail() provides the last five rows of the dataframe.

In [8]:
df.tail()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [13]:
df['A']

0    1
1    4
2    7
Name: A, dtype: int64

In [14]:
print(df['B'])

0    2
1    5
2    8
Name: B, dtype: int64

In [15]:
print(df['C'])

0    3
1    6
2    9
Name: C, dtype: int64

In [16]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [17]:
print(df.index.to_list())

[0, 1, 2]

This df.index provides the index values as a range type with step value, if we use to_list here, then they will directly convert the range index to a list..

In [18]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=['x', 'y', 'z'])
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [19]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [22]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

The df.describe helps to get some info about the dataframe.

In [24]:
df.nunique()

A    3
B    3
C    3
dtype: int64

The df.nunique helps to get the number of unique values in a column.

In [25]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [26]:
df['A'].unique()

array([1, 4, 7])

In [27]:
type(df['A'].unique())

numpy.ndarray

In [28]:
df.size

9

It returns the total number of elements in the dataframe.